"""Generate and check the decision catalog; standard-library only."""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]


def catalog():
    rows = []
    for path in sorted((ROOT / '.docflow/adr').glob('*.md')):
        if path.name.startswith('0000-'):
            continue
        raw = path.read_text(encoding='utf-8')
        match = re.match(r'^---\n(.*?)\n---', raw, re.S)
        if not match:
            raise ValueError(f'{path.name}: missing metadata')
        data = dict(re.findall(r'^([\w-]+):\s*(.*?)\s*$', match[1], re.M))
        number = f'{len(rows) + 1:04d}'
        if data.get('adr') != number or not path.name.startswith(number + '-'):
            raise ValueError(f'{path.name}: non-contiguous decision number')
        if data.get('status') not in {'Proposed','Accepted','Implemented','Superseded','Deprecated'}:
            raise ValueError(f'{path.name}: invalid status')
        shape = data.get('shape', 'capability')
        middle = ['Decision','Rationale','Consequences'] if shape == 'technology' else ['Capability statement','User stories / scenarios']
        headings = ['Context', *middle, 'Acceptance criteria','Out of scope','Open questions','References','Revision History','Approvals']
        if shape not in {'capability','technology'} or re.findall(r'^## (.+)$', raw, re.M) != headings:
            raise ValueError(f'{path.name}: sections do not match its declared shape')
        if not re.search(r'## Acceptance criteria\n\n1\. ', raw):
            raise ValueError(f'{path.name}: acceptance criteria must be numbered')
        rows.append(f'| {number} | [{data["title"]}](adr/{path.name}) | {shape} | {data["status"]} | {data["date"]} |')
    if not rows:
        raise ValueError('No decisions found')
    return '# Decision catalog\n\nGenerated by `python scripts/docflow.py`.\n\n| Number | Decision | Shape | Status | Date |\n|---|---|---|---|---|\n' + '\n'.join(rows) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = catalog()
    output = ROOT / '.docflow/INDEX.md'
    if args.check:
        if not output.exists() or output.read_text(encoding='utf-8') != expected:
            raise SystemExit('Decision catalog is stale; run python scripts/docflow.py')
    else:
        output.write_text(expected, encoding='utf-8', newline='\n')
    print('PASS: decision catalog')


if __name__ == '__main__':
    main()
